version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - 15672:15672 # admin port
      - 5672:5672 # message port
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - kafka-cluster
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
#    image: apache/kafka:3.7.2
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - 9092:9092 # plain text
#      - 9093:9093 # controller broker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka-cluster
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_NODE_ID: 1 # KRaft 모드 사용 시 노드 아이디
#      KAFKA_PROCESS_ROLES: broker,controller # KRaft 모드 시 역할 지정
#      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
#      KAFKA_CREATE_TOPICS: quickstart-events:1:1 # <topic_name>:<partitions>:<replication_factor>
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092 # 필수. KRaft 모드 시 컨트롤러도 설정
#      KAFKA_LISTENERS: PLAINTEXT://localhost:9092
#      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093 # KRaft 모드 전용. broker.id 와 설정값이 일치해야 함
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#      KAFKA_NUM_PARTITIONS: 3
#      KAFKA_LOG_DIRS: /tmp/kraft-logs
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT


networks:
  kafka-cluster:
    driver: bridge
