global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    scrape_interval: 5s
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'api-gateway-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'api-gateway-service:8000' ]
  - job_name: 'user-service'
    metrics_path: '/user-service/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'api-gateway-service:8000' ]
  - job_name: 'order-service'
    metrics_path: '/order-service/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'api-gateway-service:8000' ]
  - job_name: 'catalog-service'
    metrics_path: '/catalog-service/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'api-gateway-service:8000' ]