server:
  port: 8888 # spring cloud config default port

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/git/ecommerce-config
        git:
          uri: https://github.com/VolkaDemetrie/ecommerce-config.git
#          private-key:
#          uri: file://Users/volka/git/ecommerce-config
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

# actuator 엔드포인트 설정
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httpexchanges, busrefresh, info, metrics, prometheus
#        include: health, busrefresh